import type { Config, Erd, Flows } from '@modelwright/schema';
import { dataModelSection } from './erd';
import { flowsSection } from './flows';
import { inlineText } from './ids';

export { erdMermaid, relationshipSentences } from './erd';
export { flowsMermaid } from './flows';
export { plural } from './plural';
export {
  changeCount,
  diffDesign,
  type Change,
  type ChangeIds,
  type ChangeKind,
  type Design,
  type DesignDiff,
} from './diff';
export { DIFF_GROUPS, renderDiff } from './renderDiff';

export const SPEC_HEADER =
  'Generated by modelwright from erd.json, flows.json and config.json — don’t edit; it’s overwritten on every save.';

/**
 * `.design/spec.md`: the design in Markdown, with Mermaid diagrams GitHub renders, for people
 * and for Claude Code to read. Pure and deterministic: the same documents always give the same
 * bytes, so an unchanged design shows no diff.
 */
export function renderSpec(config: Config, erd: Erd, flows: Flows): string {
  const lines = [
    `> ${SPEC_HEADER}`,
    '',
    `# ${inlineText(config.name)}`,
    '',
    ...dataModelSection(erd),
    ...flowsSection(flows, erd),
    ...previewSection(config),
  ];
  // One trailing newline, no trailing blank lines.
  while (lines[lines.length - 1] === '') lines.pop();
  return `${lines.join('\n')}\n`;
}

function previewSection(config: Config): string[] {
  const out = ['## Preview', ''];
  const { url, devCommand } = config.preview;
  if (!url && !devCommand && !config.devices?.length) {
    out.push('No preview set.', '');
    return out;
  }
  if (url) out.push(`- URL: ${url}`);
  if (devCommand) out.push(`- Dev command: \`${devCommand.replace(/`/g, "'")}\``);
  if (config.devices?.length) {
    const devices = config.devices.map(
      (d) => `${inlineText(d.name)} (${d.width}${d.height ? ` × ${d.height}` : ''})`,
    );
    out.push(`- Devices: ${devices.join(', ')}`);
  }
  out.push('');
  return out;
}
