// @vitest-environment jsdom
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import mermaid from 'mermaid';
import { beforeAll, describe, expect, it } from 'vitest';
import {
  defaultConfig,
  defaultErd,
  defaultFlows,
  parseDesignJson,
  type Cardinality,
  type Config,
  type DesignKind,
  type Erd,
  type Flows,
} from '@modelwright/schema';
import { erdMermaid, flowsMermaid, plural, relationshipSentences, renderSpec } from '../src';
import { MERMAID_LEFT, MERMAID_RIGHT } from '../src/erd';

const here = (p: string) => fileURLToPath(new URL(p, import.meta.url));
const FIXTURES = {
  notes: here('../../schema/test/fixtures/notes'),
  busy: here('./fixtures/busy'),
};

function load(dir: string) {
  const read = <K extends DesignKind>(kind: K) => {
    const result = parseDesignJson(kind, readFileSync(`${dir}/${kind}.json`, 'utf8'));
    if (!result.ok) throw new Error(`${dir}/${kind}.json is invalid`);
    return result.doc;
  };
  return {
    config: read('config') as Config,
    erd: read('erd') as Erd,
    flows: read('flows') as Flows,
  };
}

/** Compares with the checked-in golden file; `UPDATE_GOLDEN=1` rewrites it. */
function golden(name: string, text: string) {
  const file = here(`./golden/${name}.md`);
  if (process.env.UPDATE_GOLDEN || !existsSync(file)) writeFileSync(file, text);
  expect(text).toBe(readFileSync(file, 'utf8'));
}

/** Every ```mermaid block in a spec. */
function diagrams(spec: string): string[] {
  return [...spec.matchAll(/```mermaid\n([\s\S]*?)\n```/g)].map((m) => m[1] as string);
}

beforeAll(() => {
  mermaid.initialize({ startOnLoad: false });
});

describe('renderSpec', () => {
  for (const [name, dir] of Object.entries(FIXTURES)) {
    it(`matches the golden file for the ${name} example`, () => {
      const { config, erd, flows } = load(dir);
      golden(name, renderSpec(config, erd, flows));
    });

    it(`gives byte-identical output on repeated runs (${name})`, () => {
      const a = load(dir);
      const b = load(dir);
      expect(renderSpec(a.config, a.erd, a.flows)).toBe(renderSpec(b.config, b.erd, b.flows));
    });

    it(`produces diagrams Mermaid's own parser accepts (${name})`, async () => {
      const { config, erd, flows } = load(dir);
      const found = diagrams(renderSpec(config, erd, flows));
      expect(found).toHaveLength(2);
      for (const d of found) await expect(mermaid.parse(d)).resolves.toBeTruthy();
    });
  }

  it('starts with the header line and the project name, and ends with one newline', () => {
    const { config, erd, flows } = load(FIXTURES.notes);
    const spec = renderSpec(config, erd, flows);
    expect(spec.split('\n').slice(0, 3)).toEqual([
      '> Generated by modelwright from erd.json, flows.json and config.json — don’t edit; it’s overwritten on every save.',
      '',
      '# Notes',
    ]);
    expect(spec.endsWith('\n')).toBe(true);
    expect(spec.endsWith('\n\n')).toBe(false);
  });

  it('renders empty documents sensibly, without diagrams', () => {
    const spec = renderSpec(defaultConfig('Blank'), defaultErd(), defaultFlows());
    expect(spec).toContain('No entities yet.');
    expect(spec).toContain('No screens yet.');
    expect(spec).toContain('No preview set.');
    expect(diagrams(spec)).toEqual([]);
  });

  it('marks dead-end CTAs', () => {
    const { config, erd, flows } = load(FIXTURES.notes);
    const spec = renderSpec(config, erd, flows);
    expect(spec).toContain('- **Open note** (dead end)');
    expect(spec).toContain('- **Try again** (dead end)');
    expect(spec).not.toContain('**Sign in** (dead end)');
  });

  it('lists every place a CTA leads, with transition labels', () => {
    const { config, erd, flows } = load(FIXTURES.busy);
    const spec = renderSpec(config, erd, flows);
    expect(spec).toContain(
      '- **Pay** → Check-out › Payment failed (declined); → Catalogue › Browse (paid)',
    );
    expect(spec).toContain('- **Back** → Catalogue › Browse');
    expect(spec).toContain('- **Add to cart** → Cart › Has items (item added)');
  });
});

describe('relationships', () => {
  const erdWith = (fromCard: Cardinality, toCard: Cardinality, label?: string): Erd => ({
    schemaVersion: 1,
    entities: [
      { id: 'a', name: 'Person', attributes: [] },
      { id: 'b', name: 'Category', attributes: [] },
    ],
    relationships: [
      { id: 'r', from: 'a', to: 'b', fromCard, toCard, ...(label !== undefined && { label }) },
    ],
    layout: {},
  });
  const sentence = (erd: Erd) => relationshipSentences(erd, erd.relationships[0] as never);

  it('reads both ways, with the label forward and "belongs to" back', () => {
    expect(sentence(erdWith('one', 'zero-many', 'owns'))).toBe(
      'Each Person owns zero or more Categories. Each Category belongs to exactly one Person.',
    );
  });

  it('uses "has" without a label', () => {
    expect(sentence(erdWith('zero-one', 'many'))).toBe(
      'Each Person has one or more Categories. Each Category belongs to zero or one Person.',
    );
  });

  it('words every cardinality, singular or plural to match', () => {
    const words: Record<Cardinality, string> = {
      one: 'exactly one Category',
      'zero-one': 'zero or one Category',
      many: 'one or more Categories',
      'zero-many': 'zero or more Categories',
    };
    for (const [card, phrase] of Object.entries(words) as [Cardinality, string][]) {
      expect(sentence(erdWith('one', card))).toContain(`has ${phrase}.`);
    }
    expect(sentence(erdWith('many', 'one'))).toContain('belongs to one or more People.');
  });

  it("maps every cardinality to Mermaid's symbol at its own entity's end", () => {
    const cards: Cardinality[] = ['one', 'zero-one', 'many', 'zero-many'];
    for (const from of cards) {
      for (const to of cards) {
        const line = erdMermaid(erdWith(from, to)).split('\n').at(-1);
        expect(line).toBe(`  e_a ${MERMAID_LEFT[from]}--${MERMAID_RIGHT[to]} e_b : ""`);
      }
    }
    expect(MERMAID_LEFT).toEqual({ one: '||', 'zero-one': '|o', many: '}|', 'zero-many': '}o' });
    expect(MERMAID_RIGHT).toEqual({ one: '||', 'zero-one': 'o|', many: '|{', 'zero-many': 'o{' });
  });

  it('parses every cardinality pair with Mermaid', async () => {
    const cards: Cardinality[] = ['one', 'zero-one', 'many', 'zero-many'];
    for (const from of cards) {
      for (const to of cards) {
        await expect(
          mermaid.parse(erdMermaid(erdWith(from, to, 'is "linked" to'))),
        ).resolves.toBeTruthy();
      }
    }
  });
});

describe('identifiers and text', () => {
  it('makes safe, distinct identifiers from ids with punctuation, and keeps names as labels', () => {
    const erd: Erd = {
      schemaVersion: 1,
      entities: [
        { id: 'line-item', name: 'Line item', attributes: [] },
        { id: 'line_item', name: 'Line "item" (old)', attributes: [] },
        { id: 'end', name: 'End', attributes: [] },
      ],
      relationships: [],
      layout: {},
    };
    expect(erdMermaid(erd)).toBe(
      [
        'erDiagram',
        '  e_line_item["Line item"]',
        '  e_line_item_2["Line #quot;item#quot; (old)"]',
        '  e_end["End"]',
      ].join('\n'),
    );
  });

  it('keeps Mermaid keywords and punctuation out of flowchart identifiers', async () => {
    const flows: Flows = {
      schemaVersion: 1,
      screens: [
        {
          id: 'end',
          name: 'The end?',
          states: [{ id: 'o', name: 'x', sees: [], ctas: [{ id: 'c', label: 'Go -> "there"' }] }],
        },
        { id: 'a b', name: 'subgraph', states: [{ id: 's', name: 'S', sees: [], ctas: [] }] },
      ],
      transitions: [
        { id: 't', from: { screenId: 'end', stateId: 'o', ctaId: 'c' }, to: { screenId: 'a b' } },
      ],
      layout: {},
    };
    const chart = flowsMermaid(flows);
    expect(chart).toContain('s_end["The end?"]');
    expect(chart).toContain('s_a_b["subgraph"]');
    expect(chart).toContain('s_end -->|"Go -> #quot;there#quot;"| s_a_b');
    await expect(mermaid.parse(chart)).resolves.toBeTruthy();
  });

  it('escapes table cells and inline text', () => {
    const { config, erd, flows } = load(FIXTURES.busy);
    const spec = renderSpec(config, erd, flows);
    expect(spec).toContain('| email | unique \\| lower-cased |');
    expect(spec).toContain('| status | draft, paid<br>or shipped |');
    expect(spec).toContain('- price \\| stock');
  });
});

describe('plural', () => {
  it.each([
    ['Note', 'Notes'],
    ['Category', 'Categories'],
    ['Day', 'Days'],
    ['Address', 'Addresses'],
    ['Box', 'Boxes'],
    ['Match', 'Matches'],
    ['Line item', 'Line items'],
    ['Person', 'People'],
    ['Child', 'Children'],
    ['Settings', 'Settings'],
    ['SKU', 'SKUs'],
    ['Order (v2)', 'Orders (v2)'],
  ])('%s → %s', (one, many) => {
    expect(plural(one)).toBe(many);
  });
});
