import { chmod, mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { build } from 'esbuild';

const here = path.dirname(fileURLToPath(import.meta.url));

/** Where the bundle is committed: the plugin's `bin/`, which Claude Code puts on the Bash tool's PATH. */
export const BUNDLE_PATH = path.resolve(
  here,
  '../../../plugins/modelwright/bin/modelwright-design',
);

/**
 * Builds the CLI into one self-contained Node script: every workspace package and zod bundled
 * in, nothing to install. Not minified, so a diff of the committed bundle stays readable.
 * Deterministic: the same sources always give the same bytes.
 */
export async function buildBundle(): Promise<string> {
  const result = await build({
    entryPoints: [path.resolve(here, '../src/bin.ts')],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'node24',
    write: false,
    legalComments: 'none',
    // Paths in the bundle's comments are relative to here, so they don't depend on the checkout.
    absWorkingDir: path.resolve(here, '..'),
    banner: {
      js: '#!/usr/bin/env node\n// modelwright-design — generated by `pnpm build:plugin` from packages/cli. Don’t edit.',
    },
  });
  const [file] = result.outputFiles;
  if (!file) throw new Error('esbuild produced no output');
  return file.text;
}

/** Writes the bundle into the plugin, executable. */
export async function writeBundle(): Promise<void> {
  await mkdir(path.dirname(BUNDLE_PATH), { recursive: true });
  await writeFile(BUNDLE_PATH, await buildBundle());
  await chmod(BUNDLE_PATH, 0o755);
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await writeBundle();
  console.log(`Wrote ${path.relative(process.cwd(), BUNDLE_PATH)}`);
}
